source 'https://rubygems.org'

gem 'fakefs', '~> 3.0'
gem 'fiddle'
gem 'get_process_mem'
gem 'irb'
gem 'numo-gnuplot'
gem 'numo-linalg'
gem 'numo-narray'
gem 'numo-random'
gem 'reline'
gem 'rmagick'
gem 'rspec'
gem 'ruby-prof'
gem 'ruby-vips'
gem 'sys-proctable'
gem 'terminal-table'
case RUBY_PLATFORM
when 'x86_64-linux'
  gem 'iruby'
  gem 'matplotlib'
  gem 'torch-rb'
  gem 'torchvision'
when 'x64-mingw-ucrt'
  gem 'win32ole'
end

gem 'byebug'
