source 'https://rubygems.org'

gem 'fiddle'
gem 'irb'
gem 'numo-gnuplot'
gem 'numo-linalg'
gem 'numo-narray'
gem 'numo-random'
gem 'reline'
gem 'rmagick'
gem 'rspec'
gem 'ruby-prof'
gem 'ruby-vips'
gem 'terminal-table'
if RUBY_PLATFORM == 'x86_64-linux'
  gem 'iruby'
  gem 'matplotlib'
  gem 'torch-rb'
  gem 'torchvision'
end

gem 'byebug'
