# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("onnx.proto", :syntax => :proto2) do
    add_message "onnx.AttributeProto" do
      optional :name, :string, 1
      optional :ref_attr_name, :string, 21
      optional :doc_string, :string, 13
      optional :type, :enum, 20, "onnx.AttributeProto.AttributeType"
      optional :f, :float, 2
      optional :i, :int64, 3
      optional :s, :bytes, 4
      optional :t, :message, 5, "onnx.TensorProto"
      optional :g, :message, 6, "onnx.GraphProto"
      optional :sparse_tensor, :message, 22, "onnx.SparseTensorProto"
      optional :tp, :message, 14, "onnx.TypeProto"
      repeated :floats, :float, 7
      repeated :ints, :int64, 8
      repeated :strings, :bytes, 9
      repeated :tensors, :message, 10, "onnx.TensorProto"
      repeated :graphs, :message, 11, "onnx.GraphProto"
      repeated :sparse_tensors, :message, 23, "onnx.SparseTensorProto"
      repeated :type_protos, :message, 15, "onnx.TypeProto"
    end
    add_enum "onnx.AttributeProto.AttributeType" do
      value :UNDEFINED, 0
      value :FLOAT, 1
      value :INT, 2
      value :STRING, 3
      value :TENSOR, 4
      value :GRAPH, 5
      value :SPARSE_TENSOR, 11
      value :TYPE_PROTO, 13
      value :FLOATS, 6
      value :INTS, 7
      value :STRINGS, 8
      value :TENSORS, 9
      value :GRAPHS, 10
      value :SPARSE_TENSORS, 12
      value :TYPE_PROTOS, 14
    end
    add_message "onnx.ValueInfoProto" do
      optional :name, :string, 1
      optional :type, :message, 2, "onnx.TypeProto"
      optional :doc_string, :string, 3
      repeated :metadata_props, :message, 4, "onnx.StringStringEntryProto"
    end
    add_message "onnx.NodeProto" do
      repeated :input, :string, 1
      repeated :output, :string, 2
      optional :name, :string, 3
      optional :op_type, :string, 4
      optional :domain, :string, 7
      optional :overload, :string, 8
      repeated :attribute, :message, 5, "onnx.AttributeProto"
      optional :doc_string, :string, 6
      repeated :metadata_props, :message, 9, "onnx.StringStringEntryProto"
      repeated :device_configurations, :message, 10, "onnx.NodeDeviceConfigurationProto"
    end
    add_message "onnx.IntIntListEntryProto" do
      optional :key, :int64, 1
      repeated :value, :int64, 2
    end
    add_message "onnx.NodeDeviceConfigurationProto" do
      optional :configuration_id, :string, 1
      repeated :sharding_spec, :message, 2, "onnx.ShardingSpecProto"
      optional :pipeline_stage, :int32, 3
    end
    add_message "onnx.ShardingSpecProto" do
      optional :tensor_name, :string, 1
      repeated :device, :int64, 2
      repeated :index_to_device_group_map, :message, 3, "onnx.IntIntListEntryProto"
      repeated :sharded_dim, :message, 4, "onnx.ShardedDimProto"
    end
    add_message "onnx.ShardedDimProto" do
      optional :axis, :int64, 1
      repeated :simple_sharding, :message, 2, "onnx.SimpleShardedDimProto"
    end
    add_message "onnx.SimpleShardedDimProto" do
      optional :num_shards, :int64, 3
      oneof :dim do
        optional :dim_value, :int64, 1
        optional :dim_param, :string, 2
      end
    end
    add_message "onnx.TrainingInfoProto" do
      optional :initialization, :message, 1, "onnx.GraphProto"
      optional :algorithm, :message, 2, "onnx.GraphProto"
      repeated :initialization_binding, :message, 3, "onnx.StringStringEntryProto"
      repeated :update_binding, :message, 4, "onnx.StringStringEntryProto"
    end
    add_message "onnx.ModelProto" do
      optional :ir_version, :int64, 1
      repeated :opset_import, :message, 8, "onnx.OperatorSetIdProto"
      optional :producer_name, :string, 2
      optional :producer_version, :string, 3
      optional :domain, :string, 4
      optional :model_version, :int64, 5
      optional :doc_string, :string, 6
      optional :graph, :message, 7, "onnx.GraphProto"
      repeated :metadata_props, :message, 14, "onnx.StringStringEntryProto"
      repeated :training_info, :message, 20, "onnx.TrainingInfoProto"
      repeated :functions, :message, 25, "onnx.FunctionProto"
      repeated :configuration, :message, 26, "onnx.DeviceConfigurationProto"
    end
    add_message "onnx.DeviceConfigurationProto" do
      optional :name, :string, 1
      optional :num_devices, :int32, 2
      repeated :device, :string, 3
    end
    add_message "onnx.StringStringEntryProto" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
    add_message "onnx.TensorAnnotation" do
      optional :tensor_name, :string, 1
      repeated :quant_parameter_tensor_names, :message, 2, "onnx.StringStringEntryProto"
    end
    add_message "onnx.GraphProto" do
      repeated :node, :message, 1, "onnx.NodeProto"
      optional :name, :string, 2
      repeated :initializer, :message, 5, "onnx.TensorProto"
      repeated :sparse_initializer, :message, 15, "onnx.SparseTensorProto"
      optional :doc_string, :string, 10
      repeated :input, :message, 11, "onnx.ValueInfoProto"
      repeated :output, :message, 12, "onnx.ValueInfoProto"
      repeated :value_info, :message, 13, "onnx.ValueInfoProto"
      repeated :quantization_annotation, :message, 14, "onnx.TensorAnnotation"
      repeated :metadata_props, :message, 16, "onnx.StringStringEntryProto"
    end
    add_message "onnx.TensorProto" do
      repeated :dims, :int64, 1
      optional :data_type, :int32, 2
      optional :segment, :message, 3, "onnx.TensorProto.Segment"
      repeated :float_data, :float, 4
      repeated :int32_data, :int32, 5
      repeated :string_data, :bytes, 6
      repeated :int64_data, :int64, 7
      optional :name, :string, 8
      optional :doc_string, :string, 12
      optional :raw_data, :bytes, 9
      repeated :external_data, :message, 13, "onnx.StringStringEntryProto"
      optional :data_location, :enum, 14, "onnx.TensorProto.DataLocation"
      repeated :double_data, :double, 10
      repeated :uint64_data, :uint64, 11
      repeated :metadata_props, :message, 16, "onnx.StringStringEntryProto"
    end
    add_message "onnx.TensorProto.Segment" do
      optional :begin, :int64, 1
      optional :end, :int64, 2
    end
    add_enum "onnx.TensorProto.DataType" do
      value :UNDEFINED, 0
      value :FLOAT, 1
      value :UINT8, 2
      value :INT8, 3
      value :UINT16, 4
      value :INT16, 5
      value :INT32, 6
      value :INT64, 7
      value :STRING, 8
      value :BOOL, 9
      value :FLOAT16, 10
      value :DOUBLE, 11
      value :UINT32, 12
      value :UINT64, 13
      value :COMPLEX64, 14
      value :COMPLEX128, 15
      value :BFLOAT16, 16
      value :FLOAT8E4M3FN, 17
      value :FLOAT8E4M3FNUZ, 18
      value :FLOAT8E5M2, 19
      value :FLOAT8E5M2FNUZ, 20
      value :UINT4, 21
      value :INT4, 22
      value :FLOAT4E2M1, 23
      value :FLOAT8E8M0, 24
      value :UINT2, 25
      value :INT2, 26
    end
    add_enum "onnx.TensorProto.DataLocation" do
      value :DEFAULT, 0
      value :EXTERNAL, 1
    end
    add_message "onnx.SparseTensorProto" do
      optional :values, :message, 1, "onnx.TensorProto"
      optional :indices, :message, 2, "onnx.TensorProto"
      repeated :dims, :int64, 3
    end
    add_message "onnx.TensorShapeProto" do
      repeated :dim, :message, 1, "onnx.TensorShapeProto.Dimension"
    end
    add_message "onnx.TensorShapeProto.Dimension" do
      optional :denotation, :string, 3
      oneof :value do
        optional :dim_value, :int64, 1
        optional :dim_param, :string, 2
      end
    end
    add_message "onnx.TypeProto" do
      optional :denotation, :string, 6
      oneof :value do
        optional :tensor_type, :message, 1, "onnx.TypeProto.Tensor"
        optional :sequence_type, :message, 4, "onnx.TypeProto.Sequence"
        optional :map_type, :message, 5, "onnx.TypeProto.Map"
        optional :optional_type, :message, 9, "onnx.TypeProto.Optional"
        optional :sparse_tensor_type, :message, 8, "onnx.TypeProto.SparseTensor"
      end
    end
    add_message "onnx.TypeProto.Tensor" do
      optional :elem_type, :int32, 1
      optional :shape, :message, 2, "onnx.TensorShapeProto"
    end
    add_message "onnx.TypeProto.Sequence" do
      optional :elem_type, :message, 1, "onnx.TypeProto"
    end
    add_message "onnx.TypeProto.Map" do
      optional :key_type, :int32, 1
      optional :value_type, :message, 2, "onnx.TypeProto"
    end
    add_message "onnx.TypeProto.Optional" do
      optional :elem_type, :message, 1, "onnx.TypeProto"
    end
    add_message "onnx.TypeProto.SparseTensor" do
      optional :elem_type, :int32, 1
      optional :shape, :message, 2, "onnx.TensorShapeProto"
    end
    add_message "onnx.OperatorSetIdProto" do
      optional :domain, :string, 1
      optional :version, :int64, 2
    end
    add_message "onnx.FunctionProto" do
      optional :name, :string, 1
      repeated :input, :string, 4
      repeated :output, :string, 5
      repeated :attribute, :string, 6
      repeated :attribute_proto, :message, 11, "onnx.AttributeProto"
      repeated :node, :message, 7, "onnx.NodeProto"
      optional :doc_string, :string, 8
      repeated :opset_import, :message, 9, "onnx.OperatorSetIdProto"
      optional :domain, :string, 10
      optional :overload, :string, 13
      repeated :value_info, :message, 12, "onnx.ValueInfoProto"
      repeated :metadata_props, :message, 14, "onnx.StringStringEntryProto"
    end
    add_enum "onnx.Version" do
      value :_START_VERSION, 0
      value :IR_VERSION_2017_10_10, 1
      value :IR_VERSION_2017_10_30, 2
      value :IR_VERSION_2017_11_3, 3
      value :IR_VERSION_2019_1_22, 4
      value :IR_VERSION_2019_3_18, 5
      value :IR_VERSION_2019_9_19, 6
      value :IR_VERSION_2020_5_8, 7
      value :IR_VERSION_2021_7_30, 8
      value :IR_VERSION_2023_5_5, 9
      value :IR_VERSION_2024_3_25, 10
      value :IR_VERSION_2025_05_12, 11
      value :IR_VERSION_2025_08_26, 12
      value :IR_VERSION, 13
    end
    add_enum "onnx.OperatorStatus" do
      value :EXPERIMENTAL, 0
      value :STABLE, 1
    end
  end
end

module Onnx
  AttributeProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.AttributeProto").msgclass
  AttributeProto::AttributeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.AttributeProto.AttributeType").enummodule
  ValueInfoProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.ValueInfoProto").msgclass
  NodeProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.NodeProto").msgclass
  IntIntListEntryProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.IntIntListEntryProto").msgclass
  NodeDeviceConfigurationProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.NodeDeviceConfigurationProto").msgclass
  ShardingSpecProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.ShardingSpecProto").msgclass
  ShardedDimProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.ShardedDimProto").msgclass
  SimpleShardedDimProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.SimpleShardedDimProto").msgclass
  TrainingInfoProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TrainingInfoProto").msgclass
  ModelProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.ModelProto").msgclass
  DeviceConfigurationProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.DeviceConfigurationProto").msgclass
  StringStringEntryProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.StringStringEntryProto").msgclass
  TensorAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TensorAnnotation").msgclass
  GraphProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.GraphProto").msgclass
  TensorProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TensorProto").msgclass
  TensorProto::Segment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TensorProto.Segment").msgclass
  TensorProto::DataType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TensorProto.DataType").enummodule
  TensorProto::DataLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TensorProto.DataLocation").enummodule
  SparseTensorProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.SparseTensorProto").msgclass
  TensorShapeProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TensorShapeProto").msgclass
  TensorShapeProto::Dimension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TensorShapeProto.Dimension").msgclass
  TypeProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TypeProto").msgclass
  TypeProto::Tensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TypeProto.Tensor").msgclass
  TypeProto::Sequence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TypeProto.Sequence").msgclass
  TypeProto::Map = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TypeProto.Map").msgclass
  TypeProto::Optional = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TypeProto.Optional").msgclass
  TypeProto::SparseTensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.TypeProto.SparseTensor").msgclass
  OperatorSetIdProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.OperatorSetIdProto").msgclass
  FunctionProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.FunctionProto").msgclass
  Version = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.Version").enummodule
  OperatorStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("onnx.OperatorStatus").enummodule
end
