#!/usr/bin/env ruby

# Usage: commit <comment>

require 'tmpdir'
require_relative '../helpers'

comment = ARGV[0]

raise 'Missing comment' if comment.nil?

Dir.mktmpdir do |temp_dir|
  comment_file = "#{temp_dir}/comment.txt"
  File.write(comment_file, comment.gsub('\\n', "\n") + RubyNeuralNetsTools.agent_signature)
  system "git commit --file \"#{comment_file}\"", exception: true
end

puts
puts 'Git commit created successfully'
