#!/usr/bin/env ruby

require 'json'

repo_info = JSON.parse(`gh repo view --json owner,name`)
github_handle = "#{repo_info['owner']['login']}/#{repo_info['name']}"
puts "Repository Github handle: #{github_handle}"

branch = `git branch --show-current`.strip
puts "Branch name: #{branch}"

prs_list = JSON.parse(`gh pr list --head #{branch} --json number`).map { |elem| elem['number'] }
puts "Found #{prs_list.size} Pull Requests dealing with this branch, with numbers #{prs_list.join(', ')}"

prs_list.each do |pr_number|
  puts "Comments found on Pull Request ##{pr_number}:"
  puts `gh api repos/#{github_handle}/pulls/#{pr_number}/comments`
  puts
end
